### ISSUE TITLE
Event name limited to 20 characters

### ISSUE THREAD

**Issue by GaryA** [GaryA/antlog#19]
This is not long enough to allow "Antweight World Series xx". Limit should be much longer, at least 50 and possibly 100+ characters.

**Comment by joey-picus** [comment]
Still doing this in the current production version :( I think 50 would probably be enough though, I've seen people put the date of the event in the title before...

**Comment by GaryA** [comment]
Whilst the database field and the form field had been increased in size, the validation in the model was still at 20 characters :(

**Comment by GaryA** [comment]
Fixed in commit https://github.com/GaryA/antlog/commit/ae41feb6c2e8bd972ad45b8115e399d0e490e7ef
