### ISSUE TITLE
Server IP address display

### ISSUE THREAD

**Issue by joey-picus** [GaryA/antlog#28]
Having the server IP address displayed in the title bar would make remote access at an event easier - title bar may work better than in the 'About' page (as discussed) as then it would be displayed on the projector/screen at all times and would stop people queueing up to go 'what's the address?'.

**Comment by GaryA** [comment]
Implemented in commit https://github.com/GaryA/antlog/commit/ae41feb6c2e8bd972ad45b8115e399d0e490e7ef
