### ISSUE TITLE
Importing AntLog 2 data

### ISSUE THREAD

**Issue by joey-picus** [GaryA/antlog#33]
Would it be possible to develop some sort of process to import and show results from tournaments run solely using AntLog 2 (or even AntLog 1!) to be browsed and shown in AntLog 3? If this can be done - and I can see some issues with robots that don't have an AL3 entry, or worse, where the name gets misspelled at tech check! - I think it might be good for two reasons, albeit fairly long term and low profile:

1: If (as I think would be good for everything - we need a website that shows more external signs of life) AntLog 3 is to be integrated and used to run most or all future AWS events, it would hasten adoption to allow people to still use AntLog 2 if there's computer issues or people are just confused by the web server aspect;

2: Past events can then be integrated, at least up to a point - I think when you go back in time to before people used AntLog, it intersects nicely with the point at which events get small and sensible enough to convert manually based on Oliver's site (in my current state of possibly terminal unemployment I'm happy to do this!)

**Comment by GaryA** [comment]
This would be very much a "nice to have". The more I think about it the more unlikely it feels. There is a significant amount of data missing from the Antlog 2 data to make it fit the Antlog 3 database. One would have to populate the user, robot, event, entrant and fights tables with consistent data. This would be a lot of work and not that easy to automate from the Antlog 2 data. I suspect that for may events the original data no longer exists and there is only an HTML or PDF copy which would be extremely difficult to process.
I had thought about this previously, but really only considered adding the robots and teams (possibly from Dave L's list) and maybe the events and winners, without going all the way through the fights.

**Comment by GaryA** [comment]
This is not going to happen unless someone else takes it on as a separate project. It's outside the scope of Antlog3 and would require significant effort since there are differences in the fight logic between the two versions.
