### ISSUE TITLE
GroupGridView no longer provided by 2amigos/yii2-grid-view-library

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#70]
It seems GroupGridView has been removed from the 2amigos/yii2-grid-view-library - this is seemingly required by antlog - which I've just spent an hour or so attempting to install on my (non-Windows) computer.

It appears that since 2amigos/yii2-grid-view-library:1.0.1 and newer, GroupGridView has been removed in favour of a new thing called GroupColumnsBehaviour.  Unfortunately, I've not had time to dig further.

Can I recommend changing the composer.json to refer to "2amigos/yii2-grid-view-library:~0.1" rather than the "2amigos/yii2-grid-view-library" it currently refers to?

Are pull requests welcome?

**Comment by GaryA** [comment]
Thanks for finding this, pull requests are certainly welcome! So far it's been a one-man show with very little support.

**Comment by cjsoftuk** [comment]
Ultimately - this came about as a result of me attempting to set up a machine capable of running AntLog in prep for a potential AWS53 at Southampton Uni (I am cmalton on RW101) which Dave and I have been discussing.  As an IT consultant by trade, I figured that getting this running on a Linux-based box (as I don't really use Windows at all) ought to be trivial.... and relatively speaking, it was until I discovered things like this (and the other issue I logged).

Will see if I can find some time to address some of these issues I'm logging - although I am not familiar with Yii at all.

**Comment by GaryA** [comment]
Did this come to light because you are installing Antlog via Composer? The normal route would be to download the complete Antlog package (current release zip file) which *should* contain all the correct dependencies.
See https://github.com/GaryA/antlog/wiki/Installation-Step-1

**Comment by cjsoftuk** [comment]
Err, yeah - that was exactly how I failed at that..... Was trying to work out how to make it easy to deploy a Linux virtual machine for Antlog at the click of a button - then, unless there's some essential reason for keeping it after upload, disposing of it after the files have been emailed over - so we'd be able to build a new one fresh with the latest copy before each event.

I'll be honest - yes, I probably failed to read the instructions.... but I hadn't found that page.

Combination of failure to navigate documentation - and familiarity with using composer - leads to this.

**Comment by cjsoftuk** [comment]
Looking at it... I think I probably did see that page - and promptly ignored it as it started talking about XAMPP - which is Windows - and I'm trying to do it without installing Windows.  I therefore didn't get as far as Step 2...

**Comment by GaryA** [comment]
Ha ha, you fall into the 0.1% of 0.1% of users who a) know what they're doing and b) aren't using Windows and expecting a 1-click install! Please do take a look at the wiki and/or the help in the app, it will make your life easier.On 3 Oct 2017 11:14 p.m., cjsoftuk <notifications@github.com> wrote:Err, yeah - that was exactly how I failed at that..... Was trying to work out how to make it easy to deploy a Linux virtual machine for Antlog at the click of a button - then, unless there's some essential reason for keeping it after upload, disposing of it after the files have been emailed over - so we'd be able to build a new one fresh with the latest copy before each event.
I'll be honest - yes, I probably failed to read the instructions.... but I hadn't found that page.
Combination of failure to navigate documentation - and familiarity with using composer - leads to this.
