### ISSUE TITLE
PHP Warning – yii\base\ErrorException - Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#71]
When attempting to add a robot to the database with no teams or anything present (i.e. fresh database), a PHP Warning is emitted which turns into an ErrorException.

PHP Warning – yii\base\ErrorException
Invalid argument supplied for foreach()

This is deep inside Yii and seems to be a result of passing a null to the dropDownList() function in [views/robot/_form.php:30](https://github.com/GaryA/antlog/blob/master/views/robot/_form.php#L30)

This is when running on PHP 7.0 (Nginx, Ubuntu Linux), although I suspect may occur on other platforms.

**Comment by GaryA** [comment]
Hmm, well a robot can't be added until there is a team for it to belong to. But that shouldn't cause an exception! Needs some investigation...

**Comment by cjsoftuk** [comment]
@GaryA - Yeah... I couldn't figure out how to create a team as admin..... so tried to add a robot.... Again, if I get a chance to put a PR together for it.....

**Comment by GaryA** [comment]
Teams are users but you can create teams for testing using dummy email addresses. Email is only used for password reset links. Once teams (users) exist, admin can add robots to any team. The wiki describes all this.

**Comment by cjsoftuk** [comment]
I can confirm this relates to no results being returned for the team listing.  I think it probably just needs a check: 
```
$var===null ? array() : $var
```
Will see what I can do about a patch and a PR for it.
