### ISSUE TITLE
Unable to "Close" events created locally

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#73]
It seems that events created on the local system cannot be Closed.

If running AntLog as a completely stand-alone installation (i.e. with no intent to ever upload back into the online system), it is not possible to close event registration - except by doing a database export - this seems a bizarre way to close events.

May I propose the ability to close events made locally?

**Comment by GaryA** [comment]
This is a different use case.Normally events will be created online to allow signups then downloaded to an offline server to run the event.Closing signups is linked to download of the db to ensure that the two things always happen at the same time. We don't want signups left open after the db has been downloaded or vice versa.Creating the entire database from scratch offline for every event would rather defeat the purpose. The idea of online event setup and registration is that a lot of setup time is saved at the event and teams and robots are reused, saving more time.On 4 Oct 2017 8:58 a.m., cjsoftuk <notifications@github.com> wrote:It seems that events created on the local system cannot be Closed.
If running AntLog as a completely stand-alone installation (i.e. with no intent to ever upload back into the online system), it is not possible to close event registration - except by doing a database export - this seems a bizarre way to close events.
May I propose the ability to close events made locally?

**Comment by cjsoftuk** [comment]
Cheers Gary! Thanks for this.  Makes testing things a lot, lot easier.

**Comment by GaryA** [comment]
Note this is a different use case to the normal online event creation. Events created locally are created with the status set to "Closed", i.e. online signup is closed. Signup at the event, by teams and by Admin, are still enabled right up until the draw is done.

If event results are to be uploaded to the online database it is essential that the event is created online and downloaded as this locks the online database for the duration of the event to ensure database consistency when the results are uploaded.
