### ISSUE TITLE
Unable to close registration early without downloading the database

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#74]
In the particular case of AWS53, we need to close registration early to ensure that people could not register for the event once we've submitted "final" numbers to the University.  At the moment, to do this, one must download the database.

Having added the capability to close events locally in a previous issue I raised, there are use cases (possibly rare) where being able to close events before export would be necessary.  Appreciate that in the vast majority of cases you probably don't need to - and this isn't major, but a nice-to-have if we work out the workflow for it.

**Comment by GaryA** [comment]
This is exactly how Antlog is supposed to work.
There is a simple, secure interlock such that the EO doesn't need to worry about closing the registration, they just have to download the database.
I don't see why you need to close signup without downloading the DB. The DB has to be downloaded at some point so just download it at the signup cutoff point.
Robots (and teams) can be added/deleted on the local DB on the day and will sync back to the online DB after the event.
