### ISSUE TITLE
[Feature] Fights list available via JSON

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#76]
For a number of reasons, I'd like to be able to get a feed of "Now, Next, and Future" fights (ideally with future being in order) in a JSON feed.  I'm happy to take the lead on developing this in a fork and asking for a merge when it's done.  Main reason for wanting this is so that I can sensibly plug this together with the University's projector screen for AWS53.

Appreciating that AntLog doesn't really have a concept of "current" in relation to a battle - So need to work out how to manage that.

**Comment by cjsoftuk** [comment]
I've got a working prototype of this locally - will push to a feature branch on my fork so you can have a look.

**Comment by cjsoftuk** [comment]
I've pushed this into https://github.com/cjsoftuk/antlog/tree/feature/json_fights_feed

**Comment by cjsoftuk** [comment]
This worked "OK" today at AWS53 - there's still a few bits of work to be done as the fights didn't *always* come out in the order they were on the screen in Antlog.

**Comment by cjsoftuk** [comment]
OK, the ordering bug was fixed in https://github.com/cjsoftuk/antlog/commit/43315031d28da330fd2880439d04b7fc77f4bdd8

I've done a few other misc fixes in that repo as well this evening - plan is to run it with those changes at AWS54 and see how we go.

**Comment by cjsoftuk** [comment]
AWS54 was good in terms of stability on this - no out-of-order fights that I'm aware of.  Will raise a PR for this feature to get included.

**Comment by GaryA** [comment]
Issue #92 will add a `current_fight` table to avoid the need to write files on the server.
This feature should be added in a Yii2 way, there is documentation on how to implement a RESTful API: http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html
(Use the navigation panel to go beyond the quick start page to get more details.)

**Comment by GaryA** [comment]
Having read and thought a bit further, maybe a `current_fight` table is unnecessary, perhaps just an extra boolean field in the `fights` table would be enough.
The full RESTful API is probably a bit much, but there is a "proper" Yii way to return JSON:
https://github.com/samdark/yii2-cookbook/blob/master/book/response-formats.md

**Comment by GaryA** [comment]
Issue #34 is sort-of fixed or worked round by this feature

**Comment by cjsoftuk** [comment]
The https://github.com/GaryA/antlog/tree/issue92 branch doesn't implement this in a way that's compatible with jQuery if (and only if) Antlog and the requesting page are on different domains.  In my case that's nearly always the case - and if we want to make Antlog feed other services as well, it should be easier to get JSON data out without needing to set X-Requested-With.  

Can I suggest we check the Accept: header for application/json or text/javascript and serve content based on that?

I'll put a patch together after I've had a chance to eat something.

**Comment by cjsoftuk** [comment]
Additionally, the entry in the current_fight table is not removed when the close button is clicked.

**Comment by cjsoftuk** [comment]
Finally, the "now" field is an array.  This is acceptable - however, Antlog has no provision for multi-arena use.  I will, however, be putting a feature request in for this given how AWSes are scaling and timing requirements.
