### ISSUE TITLE
Entrant list shows correct number, but incorrect set of results

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#88]
While trying to work around an issue with public antlog not downloading a full copy of the database, I started screen scraping pages off public antlog to reconstruct the database in order to allow Harry to run AWS54.

I discovered while scraping /entrant/?eventId=<x> that some results were never returned in the list and others were returned on multiple pages.

For example, in event ID 4 on public Antlog, I observed that Team Shakey has, supposedly, 4 robots entered according to /events/4.  However, in the Entrants list, only one of these entrants shows up.

I've not yet looked into why this occurs.

**Comment by cjsoftuk** [comment]
This only seems to occur if you are not logged in as an admin.....

**Comment by GaryA** [comment]
Confirmed. May only occur with the online version. Complete events don't appear to have an issue. Never found an issue with the local version when logged in as admin to do tech checks.
Needs further investigation.

**Comment by GaryA** [comment]
Only seems to occur with online version when online signup is closed (but event is not complete?).
When signup is open the robots are listed in signup order. When the event is complete entrants are listed in groups. When signup is closed but event is not complete the order is different and some entrants are duplicated (and preumably some missing). May not occur with less than 20 entrants, therefore something to do with pagination?
