### ISSUE TITLE
Apostrophes get mangled in data fields

### ISSUE THREAD

**Issue by GaryA** [GaryA/antlog#89]
When apostrophes are entered into data fields (e.g. venue location) they get converted into a string including odd ASCII characters such as Euro and TM symbols.
Apostrophes need to be escaped but this should be handled by the Yii framework.
Needs some investgation...

**Comment by cjsoftuk** [comment]
Ah.. so not just my local copy then......

**Comment by GaryA** [comment]
The £ sign also appears as ? followed by an accented u

**Comment by GaryA** [comment]
This is a character encoding error - something to do with UTF8 (or lack thereof).
However, it doesn't seem to happen now, or maybe only happens for some users.
Many robot names (created by various users) contain apostrophes which are stored and displayed properly. The £ sign also appears correct now.

**Comment by GaryA** [comment]
This can most likely be fixed by changing the database and all the tables to use utf8 character set and utf8_unicode_ci collation. The database template and demo database included with the installation will need to be updated, as well as the online database.

**Comment by GaryA** [comment]
Fixed by changes as part of version 3.1.0 release
